version: "1"
services:
- type: web
  name: Forex_Trading_24X7-1
  runtime: python
  repo: https://github.com/Basudev29/Forex_Trading_24X7
  plan: free
  envVars:
  - key: TWELVEDATA_API_KEY
    sync: false
  - key: BOT_TOKEN
    sync: false
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: python main.py
  autoDeployTrigger: commit
